sequenceDiagram
    autonumber
    participant APP as 💻 App
    participant KC as ☕ KafkaConsumer
    participant K as ⚡ Cluster Kafka

    rect rgb(250, 250, 250)
        APP->>KC: 1️⃣ new KafkaConsumer(config)
        APP->>KC: 2️⃣ subscribe([topic])

        loop ♾️ Boucle infinie
            APP->>KC: 3️⃣ poll(Duration)
            KC->>K: requêtes vers brokers leaders
            K-->>KC: messages
            KC-->>APP: ConsumerRecords<K,V>
            APP->>APP: 4️⃣ traite chaque record<br/>(key, value, partition...)
        end
    end